/* 
	The do statement works sort of like a label which you can jump to
	using continue or to the end using break which also allows the user
	any sort of looping they please.
*/
main : int () => {
	foo: int = pow(2, 5);
	show(foo);
}

pow: int (base: int, exponent: int) => {
	if (exponent == 0)
		return 1;
	else if (base == 1)
		return 1;
	else if (base == 0)
		return 0;

	res: int = base;
	do {
		if ((--exponent) == 0)
			break;
		res = res * base;
		continue;
	};
	return res;
}
